name: Ubuntu VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Update and Install Required Packages
        run: |
          echo "Updating system and installing necessary packages..."
          sudo apt update && sudo apt install -y openssh-server net-tools

      - name: Configure SSH Server
        run: |
          echo "Configuring SSH server..."
          sudo sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          echo "root:password" | sudo chpasswd
          sudo service ssh start

      - name: Display VPS Details
        run: |
          echo "Fetching VPS details..."
          IP=$(hostname -I | awk '{print $1}')
          echo "=========================================="
          echo "VPS Details:"
          echo "IP Address: $IP"
          echo "Port: 2222"
          echo "Username: root"
          echo "Password: password"
          echo "=========================================="

      - name: Keep VPS Running
        run: |
          echo "Keeping the VPS running..."
          while true; do sleep 30; done
