name: RDP Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest

    steps:
      - name: Update and Install XRDP
        run: |
          echo "Updating system..."
          sudo apt update && sudo apt install -y xrdp xfce4 xfce4-goodies
          echo "Configuring XRDP..."
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Configure Desktop Environment
        run: |
          echo "Setting up desktop environment..."
          echo xfce4-session > ~/.xsession
          sudo service xrdp restart

      - name: Set RDP Credentials
        run: |
          echo "Setting up RDP user credentials..."
          sudo useradd -m -s /bin/bash rdpuser
          echo "rdpuser:password" | sudo chpasswd
          echo "User: rdpuser, Password: password"

      - name: Display Server Info
        run: |
          echo "Fetching server details..."
          IP=$(hostname -I | awk '{print $1}')
          echo "=========================================="
          echo "RDP Server Details:"
          echo "IP Address: $IP"
          echo "Port: 3389"
          echo "Username: rdpuser"
          echo "Password: password"
          echo "=========================================="

      - name: Keep Runner Alive
        run: |
          echo "Keeping the RDP session running..."
          while true; do sleep 30; done
